#'@export
#'@import pROC
#'@title Plot ROC curves and the area under value
#'@description uses pROC library to plot ROC curve and Cardinal to plot corresponding ion image for top n discriminant markers
#'@param cardinaldata MSImageSet containing pixels and intensity data for ROC calculation
#'@param roc_curves list of pROC objects generated by rocIMS function
#'@param top_n vector of mz values to run ROC calculation, or 'all' to run on all mzs in dataset
#'@param ... passed to Cardinal::image(), useful for passing a layout to the resultant plot grid
#'@return plots of ion images and ROC curves


plotROCmz <- function(cardinaldata, roc_curves, top_n = 10,...){

  top_mzs = as.numeric(head(names(roc_curves), n = top_n))

  #plot top ranked, also may inherit layout from from function call here here
  image(cardinaldata, mz=top_mzs[1], strip=F, main = paste0('rank: 1 - m/z ',top_mzs[1]),...)
  plot.roc(roc_curves[[1]], print.auc=T, main = paste0('rank: 1 - m/z ',top_mzs[1]))

  for(i in 2:top_n){
    image(cardinaldata, mz=top_mzs[i], strip=F, main = paste0('rank: ',i,' - m/z ',top_mzs[i]))
    plot.roc(roc_curves[[i]], print.auc=T, main = paste0('rank: ',i,' - m/z ',top_mzs[i]))

  }

}
